# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:
- script: |
      try
         {
          -Uri "$(AppCIRepository)/items?path=./backup.ps1 -PathIsWebApp"
         }
      catch
         {
          write-Host 'Error occured '
         }



